### PR TITLE
ntpd by default on Raspberry PI

### PR DESCRIPTION
**Pull request by dinapappor**
Since Rapsberry PI does not have a RTC and needs ntp to keep clock in sync this PR should have that started by default.

### CODE REVIEW

**Comment by kientzle** [comment]
Could you please also add ntpd_sync_on_start?  I believe that's also essential to get ntpd to actually startup correctly.

Thanks!

**Comment by dinapappor** [comment]
Yes I can. :)

**Comment by kientzle** [comment]
On further consideration, I would rather not make this change by default, since it's quite troublesome if you are running RPi or RPi2 without a network connection.

I've edited the rc.conf files to included a commented-out version of this setting as a suggestion.
I've also added the ntpd_sync_on_start flag, which is essential for correct ntpd operation on systems without RTC.

If you want to set ntpd by default on your personal builds, it's easy to add the following to your config.sh:

```
customize_freebsd_partition ( ) {
    cat << "EOF" >> etc/rc.conf
ntpd_enable="YES"
EOF
}
```

**Comment by brd** [comment]
@kientzle Why not make it an option?

**Comment by kientzle** [comment]
Good idea!

Done in commit ec554aa

**Pull request closed without merging**
