### PR TITLE
 Add a new variable FREEBSD_MAKE_JOBS which contain the number of make j...

### PR DESCRIPTION
**Pull request by evadot**
...obs

 Default to hw.ncpu

### CODE REVIEW

**Comment by kientzle** [comment]
KERNJOBS and WORLDJOBS already exist for this purpose.

But they should be documented in config.sh.sample.

**Comment by brd** [comment]
@kientzle What do you think about setting the default to `sysctl -n hw.ncpu` though? I think it would be pretty useful for users.

**Comment by kientzle** [comment]
Yes, it would make sense to initialize WORLDJOBS and KERNJOBS based on the sysctl.

Would you please change this to:
   * Initialize WORLDJOBS and KERNJOBS
   * Document them in config.sh.sample

Thank you!

**Comment by kientzle** [comment]
This was handled in a slightly different way in commit 392ab2b.

**Pull request closed without merging**
