### PR TITLE
Add support to build images for Raspberry Pi 2

### PR DESCRIPTION
**Pull request by loos-br**
Add a new function to test the existence of u-boot ports.

Add a new board template for Raspberry Pi 2.

### CODE REVIEW

**Comment by brd** [comment]
Excellent, I will test this tonight!

**Comment by loos-br** [comment]
There are still some problems on FreeBSD side.
You need build the kernel with 'options ARM_NEW_PMAP' and disable the build of framebuffer driver (or add a 'return (ENXIO)' early on bcm_fb_attach() (in bcm2835_fbd.c).
I'm working on a fix for framebuffer.

**Comment by brd** [comment]
Why not add the ARM_NEW_PMAP to the RPI2 config in HEAD? If it is required, it seems to make sense to just have it there in the stock kernel.

**Comment by kientzle** [comment]
Nicely done!

**Pull request merged**
