### PR TITLE
Add generic firmware support

### PR DESCRIPTION
**Pull request by DianeBruce**
Add firmware support for Raspberry Pi3

### CODE REVIEW

**Comment by brd** [comment]
Did you test building an image with these changes?

**Comment by DianeBruce** [comment]
On Mon, Apr 09, 2018 at 10:09:51AM -0700, Brad Davis wrote:
> Did you test building an image with these changes?

Yes and it looks fine. But if you have been watching #bsdmips gonzo's
changes to u-boot have broken things.

Guess we are both looking at it....


-- 
- db@FreeBSD.org db@db.net http://www.db.net/~db

**Comment by cheasy** [comment]
Checked Raspberry Pi 3 build against 12.0-CURRENT @ r331740. Compile dies during building he clang compiler in base.

**Comment by brd** [comment]
@DianeBruce It is missing some changes then.

**Comment by brd** [comment]
Committed, thanks.

**Pull request closed without merging**
